spring:
    profiles: dev
    datasource:
            url: jdbc:postgresql://localhost:5432/civilizations
            username: postgres
            password: sOLEDAd04011981
            driver-class-name: org.postgresql.Driver

server:
    port: 9002

---

spring:
    profiles: postgres
    datasource:
            url: jdbc:postgresql://localhost:5432/ml_civilizations
            username: postgres
            password:
            driver-class-name: org.postgresql.Driver

server:
    port: 9002
