spring:
    profiles: default
    datasource:
            url: jdbc:mysql://localhost:3306/ml_civilizations?useSSL=false
            username: root
            password: sOLEDAd04011981$%()!
            testWhileIdle: true
            validationQuery: SELECT 1
            driver-class-name: com.mysql.jdbc.Driver

server:
    port: 9002

---

spring:
    profiles: production
    datasource:
            url: jdbc:postgresql://localhost:5432/civilizations
            username: postgres
            password: sOLEDAd04011981
            driver-class-name: org.postgresql.Driver

server:
    port: 9002
